sudo: false # faster builds
os: linux
dist: focal
arch: arm64-graviton2
virt: lxd
group: edge

language: java
jdk: openjdk11

install: true

before_script:
  - chmod +x gradlew

script:
  - gradle check -p server
  - gradle codeCoverageReport -p server

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"