### GET request with parameter
GET http://localhost:9876/api/v1/datasets/1
Accept: application/json

### GET request with parameter
GET http://localhost:9876/api/v1/datasets?keyword=n


### GET request with parameter
GET http://localhost:9876/api/v1/datasets/MINIST/files
Accept: application/json

### 1. request github user
POST https://github.com/login/device/code
Content-Type: application/json
Accept: application/json

{
"client_id" :"",
"scope":"user"
}

### 3. get user access_token from
POST https://github.com/login/oauth/access_token
Content-Type: application/json
Accept: application/json

{
"client_id" : "",
"device_code" : "",
"grant_type" : "urn:ietf:params:oauth:grant-type:device_code"
}

### get user info from token
GET https://api.github.com/user
Authorization: token



### get user info from token
GET https://api.github.com/user
Authorization: token


### odi process
### 1. request github user
GET http://localhost:9876/api/v1/login/github/device/code

### odi process
### 1. request github user
GET http://localhost:9876/api/v1/datasets/MNISTTEST/files/upload

### GET request with parameter
GET http://47.103.90.26:9876/health/check
Accept: application/json

### GET request with parameter
GET http://47.103.90.26:9876/api/v1/datasets/1
Accept: application/json


### aws
### GET request with parameter
GET http://52.53.217.38:9876/health/check
Accept: application/json

### GET request with parameter
GET http://52.53.217.38:9876/api/v1/datasets/MNISTTEST/files/upload
Accept: application/json
